--create table Customer
--(Cno int,
--Cname varchar(50)
--,Cmobile_no varchar(50),
--Ctime_date varchar(50),
--Product_type varchar(50),
--Product_Name varchar(50),
--Product_quantity varchar(50),
--Product_quality varchar(50))


--create table Employee
--(Eno int,
--Ename varchar(50),Eaddress varchar(50),
--Econtact_no  varchar(50),Epancard varchar(50),
--EjoiningDate varchar(50))

--create table Stock
--(Sno int,Product_Name varchar(50),
--Product_Type varchar(50),
--New_Quantity varchar(50),
--Old_Quantity varchar(50),
--Total_Quantity varchar(50),
--Product_Cost varchar(50),
--Company_name varchar(50),
--Company_Address varchar(50),
--Company_Contact varchar(50),
--Time_date varchar(50),
--Product_Quality varchar(50))

--create table 
--Supplier(Suno int,
--SuName varchar(50),
--SuMobile varchar(50),
--SuAddress varchar(50),
--SuCompanyName varchar(50),
--SuCompanyAddress varchar(50),
--Product_Cost varchar(50),
--Product_Quantity varchar(50),
--Product_Quality varchar(50),
--Time_date varchar(50))

--create table Bill(
--BillNo int,
--time_Date varchar(50),
--CName varchar(50),
--Mobile_no varchar(50),
--Product_name varchar(50),
--Product_type varchar(50),
--Product_Quantity varchar(50),
--Product_Quality varchar(50),
--Product_Cost varchar(50),
--Making_Cost varchar(50),
--VAT varchar(50),
--Total_Cost varchar(50))
